"""empty message

Revision ID: 7a4b8d5f2c46
Revises: 85f4e1d5f678
Create Date: 2018-03-21 12:01:19.140824

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a4b8d5f2c46'
down_revision = '85f4e1d5f678'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('q1_answer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('answer_text', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('q2_answer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('answer_text', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('q3_answer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('answer_text', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('variants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('variant_name', sa.String(length=5000), nullable=True),
    sa.Column('variant_size', sa.String(length=100), nullable=True),
    sa.Column('variant_id', sa.String(length=50000), nullable=True),
    sa.Column('image_name', sa.String(length=5000), nullable=True),
    sa.Column('igv_image', sa.String(length=50000), nullable=True),
    sa.Column('gEval_image', sa.String(length=50000), nullable=True),
    sa.Column('svviz_DotPlot_image', sa.String(length=50000), nullable=True),
    sa.Column('svviz_PB_image', sa.String(length=50000), nullable=True),
    sa.Column('svviz_Ill250_image', sa.String(length=50000), nullable=True),
    sa.Column('svviz_Ill300x_image', sa.String(length=50000), nullable=True),
    sa.Column('svviz_10X_image', sa.String(length=50000), nullable=True),
    sa.Column('svviz_MP_image', sa.String(length=50000), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('form_responses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user', sa.Integer(), nullable=True),
    sa.Column('variant', sa.Integer(), nullable=True),
    sa.Column('q1_answer', sa.Integer(), nullable=True),
    sa.Column('q2_answer', sa.Integer(), nullable=True),
    sa.Column('q3_answer', sa.Integer(), nullable=True),
    sa.Column('q4_answer', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['q1_answer'], ['q1_answer.id'], ),
    sa.ForeignKeyConstraint(['q2_answer'], ['q2_answer.id'], ),
    sa.ForeignKeyConstraint(['q3_answer'], ['q3_answer.id'], ),
    sa.ForeignKeyConstraint(['variant'], ['variants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('form_responses')
    op.drop_table('variants')
    op.drop_table('q3_answer')
    op.drop_table('q2_answer')
    op.drop_table('q1_answer')
    # ### end Alembic commands ###
